amg:
  adapter: "hci0"
  mac: "60:09:C3:1F:DC:1A"
  name: null
  start_uuid: "6e400003-b5a3-f393-e0a9-e50e24dcca9e"
  write_uuid: "6e400002-b5a3-f393-e0a9-e50e24dcca9e"
  init_cmds: []
  commands:
    beep:
      text: "BEEP"
    test_raw_aa10:
      hex: "AA-10"

sensors:
  - plate: "P1"
    adapter: "hci0"
    mac: "F8:FE:92:31:12:E3"
    notify_uuid: "0000ffe4-0000-1000-8000-00805f9a34fb"
    config_uuid: "0000ffe9-0000-1000-8000-00805f9a34fb"
    idle_reconnect_sec: 300.0
    keepalive_batt_sec: 30.0
    reconnect_initial_sec: 0.1
    reconnect_max_sec: 2.0

detector:
  triggerHigh: 0.05
  triggerLow: 0.01
  ring_min_ms: 10
  dead_time_ms: 50
  warmup_ms: 2000
  baseline_min: 1e-6
  min_amp: 0.01

logging:
  dir: "./logs"
  file_prefix: "bridge"