# amg:
#   adapter: "hci0"
#   mac: "60:09:C3:1F:DC:1A"
#   name: null
#   start_uuid: "6e400003-b5a3-f393-e0a9-e50e24dcca9e"
#   write_uuid: "6e400002-b5a3-f393-e0a9-e50e24dcca9e"
sensors:
  - plate: "P1"
    adapter: "hci0"
    mac: "F8:FE:92:31:12:E3"
    notify_uuid: "0000ffe4-0000-1000-8000-00805f9a34fb"
    config_uuid: "0000ffe9-0000-1000-8000-00805f9a34fb"
detector:
  triggerHigh: 0.05   # Very low threshold - any movement triggers
  triggerLow: 0.01    # Minimal threshold for release
  ring_min_ms: 10     # Shorter minimum detection time
  dead_time_ms: 50    # Shorter dead time between hits
  warmup_ms: 100      # Reduced warmup time
  baseline_min: 1e-6  # Very low baseline minimum
  min_amp: 0.01       # Critical: allow very small amplitudes
logging:
  dir: "./logs"
  file_prefix: "bridge"